spring:
  application:
    name: pokedex

  # Server configuration
  server:
    port: 8080

# PokeAPI configuration
pokeapi:
  base:
    url: https://pokeapi.co/api/v2

# FunTranslations API configuration
funtranslations:
  base:
    url: https://api.funtranslations.com

# Logging
logging:
  level:
    root: INFO
    com.homechallenge: DEBUG

